// Marcas de motos más usadas en México.
// Para agregar una nueva marca, añade una entrada al arreglo en orden alfabético.
export const MOTORCYCLE_BRANDS = [
  'Aprilia',
  'Bajaj',
  'Benelli',
  'Beta',
  'BMW',
  'Carabela',
  'CFMoto',
  'Ducati',
  'Harley-Davidson',
  'Hero',
  'Honda',
  'Husqvarna',
  'Italika',
  'Kawasaki',
  'KTM',
  'KYMCO',
  'Lifan',
  'Maverick',
  'Royal Enfield',
  'Suzuki',
  'Triumph',
  'TVS',
  'Vento',
  'Yamaha',
  'Zongshen',
]
