// Marcas de motos más usadas en México.
// Para agregar una nueva marca, añade una entrada al arreglo en orden alfabético.
export const MOTORCYCLE_BRANDS = [
  'Aprilia',
  'Bajaj',
  'BDS',
  'Benelli',
  'Beta',
  'BMW',
  'Carabela',
  'CFMoto',
  'Dinamo',
  'Ducati',
  'Harley-Davidson',
  'Hero',
  'Honda',
  'Husqvarna',
  'Italika',
  'Kawasaki',
  'KIWO',
  'KTM',
  'KYMCO',
  'Lifan',
  'Maverick',
  'MB',
  'MORBIDELLI',
  'Motorstreck',
  'Royal Enfield',
  'Suzuki',
  'Tribu',
  'Triumph',
  'TVS',
  'UM',
  'Veloci',
  'Vento',
  'Yamaha',
  'Zongshen',
]
